version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "feature/version-bump"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "react-router-dom"
          - "@types/react"
          - "@types/react-dom"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
      tailwind:
        patterns:
          - "tailwindcss"
          - "postcss"
          - "autoprefixer"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "feature/version-bump"
    schedule:
      interval: "weekly"
